In [1]:
#Exercicio 1

import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 16.6 ms, sys: 8.09 ms, total: 24.7 ms
Wall time: 42.3 ms
CPU times: user 775 ms, sys: 148 ms, total: 923 ms
Wall time: 925 ms


In [2]:
#Exercicio 2

import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[5:8]
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Exercico 3

import numpy as pd

arr3d = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], 10, 11, 12]])
arr3d

<ipython-input-4-d3c65f364e74>:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr3d = np.array([[[1, 2, 3], [4,5,6]], [[7,8,9], 10, 11, 12]])


array([list([[1, 2, 3], [4, 5, 6]]), list([[7, 8, 9], 10, 11, 12])],
      dtype=object)

In [5]:
arr3d[0]

[[1, 2, 3], [4, 5, 6]]

In [6]:
#Exercicio 4
arr2d = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Imprima os elementos da terceira linha da matriz
arr2d[2]

array([7, 8, 9])

In [8]:
#impirma todos os elementos da primeira e segunda linhas e segunda e terceira colunas
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [9]:
#Exercicio 5
#Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [11]:
#Exercicio 6
#Considerando os 3 arrays abaixo
#Retorne o valor do array xarr se o valor for True no array cond. Caso contrario retorne o valor de yarr
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [12]:
for x, y,c in zip(xarr, yarr, cond):
    print(x,y,c)

1.1 2.1 True
1.2 2.2 False
1.3 2.3 True
1.4 2.4 True
1.5 2.5 False


In [13]:
resultado = [(x if c else y) for x,y,c in zip(xarr, yarr, cond)]
resultado

[1.1, 2.2, 1.3, 1.4, 2.5]

In [14]:
#Exercicio 7
a = np.arange(10)
print(a)
np.save('array_a',a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
b = np.load('array_a.npy')
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
#Exercicio 8
import pandas as pd
obj = pd.Series(['c','a','d','a','a','b','b','c','c','a','b'])

In [19]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [20]:
#Exercio 9
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
resp

<Response [200]>

In [22]:
data = resp.json()
data[0]['title']

'BUG: Index.equals different behavior for EA vs non-EA types'

In [23]:
issues = pd.DataFrame(data, columns = ['number', 'title','labels','state'])
issues

number                                              title  \
0    46164  BUG: Index.equals different behavior for EA vs...   
1    46163         PERF: support mask in libgroupby.group_nth   
2    46162  Bug Fix GroupBy.describe produces inconsistent...   
3    46161                              Update test_fillna.py   
4    46156         BUG: MultiIndex slicing with negative step   
5    46154  BUG: Converting `pd.Timestamp.min` to equivale...   
6    46152     BUG: Styler cannot accept semicolon in CSS val   
7    46149  PERF: Series.fillna (that is part of DataFrame...   
8    46147                          ENH: Enumeration grouping   
9    46145  BUG: dataframe/series.isna().sum() overcounts ...   
10   46144    CI/TST: Flaky test `test_union_different_types`   
11   46142         REF: combine masked_cummin_max, cummin_max   
12   46141                  [WIP] DataFrame exchange protocol   
13   46140         Bug fix extension array with 2d datetime64   
14   46138  BUG: NotImplementedError: Cannot apply ufunc <...   
15   46137                   CLN: Remove Categorical.itemsize   
16   46135  BUG: rolling with axis=1, win_type=, and cente...   
17   46133                              TYP: groupby, sorting   
18   46132  BUG: rolling aggregate() with a list of functi...   
19   46129     BUG: df.plot(kind='barh') does not show xlabel   
20   46126  ENH: Conversion function errors kwarg callback...   
21   46122  ENH: Add option to specify table captions to b...   
22   46116               [WIP] perf improvements for strftime   
23   46114  DOC: Add note for tail/head when n is larger t...   
24   46112  BUG: DataFrame.to_json does not take into acco...   
25   46111  BUG: cannot use registered float16 extension d...   
26   46105                ENH: allow concat of Styler objects   
27   46104               ENH: IntegerArray bitwise operations   
28   46101  Add missing __finalize__ calls in indexers/ite...   
29   46100  ENH: Retrieve SqlAlchemy Mapped Attributes wit...   

                                               labels state  
0   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
1                                                  []  open  
2   [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
3   [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
6   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
7   [{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1M...  open  
8   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
11  [{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
12  [{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...  open  
13  [{'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEw...  open  
14  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
15  [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
20  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
21  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
22  [{'id': 211840, 'node_id': 'MDU6TGFiZWwyMTE4ND...  open  
23  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
27  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
28  [{'id': 1539579994, 'node_id': 'MDU6TGFiZWwxNT...  open  
29  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open

In [25]:
#Exercicio 10
import sqlite3
import pandas as pd
query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20),
 ESTADO VARCHAR(20),
 taxa REAL,
 Impostos INTEGER
);"""
conn = sqlite3.connect('dsa.db')
conn.execute(query)
conn.commit()

In [27]:
data = [('Natal', 'Rio Grande do Note', 1.25, 6),
        ('Recife', 'Pernanbuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
stmt = "INSERT INTO TESTE VALUES(?,?,?,?)"
conn.executemany(stmt, data)
conn.commit()

In [28]:
cursor = conn.execute('SELECT * FROM teste')
rows = cursor.fetchall()
rows

[('Natal', 'Rio Grande do Note', 1.25, 6),
 ('Recife', 'Pernanbuco', 2.6, 3),
 ('Londrina', 'Paraná', 1.7, 5)]

In [29]:
cursor.description
pd.DataFrame(rows, columns = [x[0] for x in cursor.description])

Cidade              ESTADO  taxa  Impostos
0     Natal  Rio Grande do Note  1.25         6
1    Recife          Pernanbuco  2.60         3
2  Londrina              Paraná  1.70         5